// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	ips "github.com/mborroni/dreamlab-challenge/internal/ipAddresses"
	reflect "reflect"
)

// Mockservice is a mock of service interface
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *Mockservice) List(arg0 context.Context, arg1 int, arg2 map[string]interface{}) ([]*ips.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*ips.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockserviceMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockservice)(nil).List), arg0, arg1, arg2)
}

// Get mocks base method
func (m *Mockservice) Get(arg0 context.Context, arg1 string) (*ips.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*ips.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockserviceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockservice)(nil).Get), arg0, arg1)
}

// GetTopNISPByCountry mocks base method
func (m *Mockservice) GetTopNISPByCountry(arg0 context.Context, arg1 int, arg2 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopNISPByCountry", arg0, arg1, arg2)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopNISPByCountry indicates an expected call of GetTopNISPByCountry
func (mr *MockserviceMockRecorder) GetTopNISPByCountry(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopNISPByCountry", reflect.TypeOf((*Mockservice)(nil).GetTopNISPByCountry), arg0, arg1, arg2)
}

// GetIPQuantityByCountry mocks base method
func (m *Mockservice) GetIPQuantityByCountry(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPQuantityByCountry", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPQuantityByCountry indicates an expected call of GetIPQuantityByCountry
func (mr *MockserviceMockRecorder) GetIPQuantityByCountry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPQuantityByCountry", reflect.TypeOf((*Mockservice)(nil).GetIPQuantityByCountry), arg0, arg1)
}
